# export FLASH_ATTENTION_DISABLE_HDIM64=TRUE
export FLASH_ATTENTION_DISABLE_HDIM96=TRUE
export FLASH_ATTENTION_DISABLE_HDIM128=TRUE
export FLASH_ATTENTION_DISABLE_HDIM192=TRUE
export FLASH_ATTENTION_DISABLE_HDIM256=TRUE
export FLASH_ATTENTION_DISABLE_FP8=TRUE
export FLASH_ATTENTION_DISABLE_SOFTCAP=TRUE
export FLASH_ATTENTION_DISABLE_PACKGQA=TRUE
export FLASH_ATTENTION_DISABLE_LOCAL=TRUE
export FLASH_ATTENTION_DISABLE_PAGEDKV=TRUE
export FLASH_ATTENTION_DISABLE_SM80=TRUE
export TORCH_CUDA_ARCH_LIST="8.9"

export PYTHONPATH=$PYTHONPATH:.
pytest -vs test_flash_attn.py::test_flash_attn_output
# pytest -vs test_flash_attn.py::test_flash_attn_output[4224-4224-256-False-True-False-15.0-False-False-gqa-dtype1]